import "./KandaStyle.css";
import yuddha1 from "../../assets/images/yuddha1.png";
import yuddha2 from "../../assets/images/yuddha2.png";
import yuddha3 from "../../assets/images/yuddha3.png";
import yuddha4 from "../../assets/images/yuddha4.png";
import yuddha5 from "../../assets/images/yuddha5.png";
import yuddha6 from "../../assets/images/yuddha6.png";
import yuddha7 from "../../assets/images/yuddha7.png";
import yuddha8 from "../../assets/images/yuddha8.png";
import yuddha9 from "../../assets/images/yuddha9.png";
import yuddha10 from "../../assets/images/yuddha10.png";
import yuddha11 from "../../assets/images/yuddha11.png";
import yuddha12 from "../../assets/images/yuddha12.png";

function YuddhaKanda() {
  return (
    <div className="kanda-page yuddha">
      <h2>Yuddha Kanda</h2>
      <div className="kanda-story">
          <p>
            <br />Hanuman landed softly on the shores of Kishkindha where Rama and Lakshmana waited, their eyes tired with longing yet shining with fragile hope. His body was covered with ash, blood, and scorched fur, but his spirit burned like a flame that no storm could extinguish. He stepped forward, folded his hands, and with a voice trembling between pride and emotion, he said, “My lord… I have seen her. I have seen Mother Sita.”<br />
            <br />Rama’s breath halted. Lakshmana’s fingers tightened around his bow as though the words might vanish if not held with strength. Rama stepped closer, his lips parted, his voice barely a whisper, “Is she… alive?” Hanuman bowed deeper. “Yes, my lord. She lives. She waits for you in Lanka, under the cruel watch of Ravana, in the Ashoka Vatika. She is frail, but her faith in you is unbroken. She sent this as proof.” From the folds of his cloth, he offered Rama the tiny jewel Sita had given him—her choodamani.<br />
            <br />Rama took it with hands that trembled, like a man who held both agony and hope in a single breath. He pressed it against his forehead and closed his eyes. Memories of Sita—the sound of her laughter, the warmth of her presence, the promise of protection he once gave her—flashed like lightning in a storm-dark sky. Tears fell, silently at first, then like rain that could no longer be held back.<br />
            <img src={yuddha1} id="img1" className="float-right" alt="" />
            <br />Hanuman told them everything—how Sita sat beneath the Shimshupa tree, how Ravana tried to break her spirit, how she refused to eat, saying, “Let Rama come. I will wait until he comes or until my breath leaves me.” Rama listened without blinking, as if each word was carved into his soul. At last he stood, his face solemn, the softness of sorrow now hardened into purpose. “We march to Lanka.”<br />
            <br />The Vanara army gathered—countless warriors standing across the coastline, the sea wind fluttering their flags. Sugriva roared commands, Angada stood mighty, Jambavan calm and wise. The ocean stretched before them, vast, untamed. They needed a way across. For the first time in days, Rama turned his eyes upward and prayed—not for victory, not for power, but for the chance to hold Sita alive again.<br />
            <br />For three days and nights, Rama sat on the sandy shore, deep in meditation. The waves crashed relentlessly, as if answering his silence. Then, rising with divine grace, emerged the god of the ocean. Folding his hands respectfully, he said, “I cannot part my waters, O Rama, but I can show you how to cross. Build a bridge across me, and I will hold it as my sacred duty.”<br />
            <br />Nala, the engineer son of the divine architect Vishwakarma, stepped forward. “I know how to build such a bridge.” And so, stones were brought from forests and mountains. Huge boulders carved with Rama’s name were thrown into the sea—stones that should have drowned floated instead. The Vanaras cried aloud in wonder, and the bridge to Lanka slowly emerged, like a silver line across the blue expanse. Day and night they worked, until on the fifth day, a path strong enough for the army stood shining beneath the sun.<br />
            <img src={yuddha2} id="img2" className="float-left" alt="" />
            <br />As they reached the island, Lanka rose before them—a city of towering walls and golden domes, now darkened by Ravana’s arrogance. Inside, Sita sat silently beneath the ashoka tree, praying to the wind, to the sky, to Rama’s heart, whispering that she was waiting.<br />
            <img src={yuddha3} id="img3" className="float-right" alt="" />
            <br />Ravana stood upon his palace balcony, his ten heads raised in pride, his eyes burning with fury. He had heard the news—the bridge, the army, the arrival of Rama. His court trembled. His brother Vibheeshana stepped forward, begging, “Return Sita, brother. End this before it destroys us all.” But Ravana’s laughter echoed like thunder. “I am Ravana! Conqueror of gods! I will not bow to a mortal man in exile.” In that moment, Vibheeshana fell to his knees, tears streaming. “Then I will leave you. I choose dharma over blood.” Ravana’s rage consumed him. “Leave before I crush you.” Vibheeshana left Lanka and walked alone toward Rama’s camp.<br />
            <br />The Vanaras blocked his path, arrows aimed. But Vibheeshana raised his hands. “I seek refuge in Rama.” Sugriva was suspicious, but Rama said gently, “If a person comes with a sincere heart, asking for shelter—even if he was once an enemy—it is my duty to protect him.” He embraced Vibheeshana, and in that act, gave him more honor than Ravana ever had.<br />
            <br />The night before the war, silence covered the camps like a blanket of smoke. Some Vanaras sharpened their weapons; others whispered prayers. Rama stood alone, looking toward Lanka, a single tear in his eye—but the tear held not weakness, but love. For Sita. For the promise he once made beneath the shade of forest trees.<br />
            <img src={yuddha4} id="img4" className="float-left" alt="" />
            <br />At dawn, the conch shells blew. The ground shook with the drums of war. The sky filled with arrows and the roars of Vanaras leaping into battle. The air smelled of trampled earth, blood, and burning hopes. Battle after battle raged—giants, demons, warriors, and kings falling on both sides. Angada leapt into the enemy ranks like a blazing wind. Hanuman struck down warriors with mountains in his hands. Lakshmana, fierce and calm, was a drenched flame of fury and devotion by his brother’s side.<br />
            <img src={yuddha6} id="img6" className="float-right" alt="" />
            <br />Ravana sent his son Indrajit—master of illusions, fearless in battle. Indrajit disappeared into the clouds, raining arrows made of fire and poison. Rama and Lakshmana fought fiercely, but Indrajit unleashed the Nagastra—the serpent weapon. Thousands of writhing serpents formed from arrows, binding the brothers to the ground. They collapsed, breathless. The world froze. Even the wind refused to move. The Vanaras fell into despair. Hanuman knelt beside Rama, tears staining his cheeks. “No… this cannot be the end.”<br />
            <br />But Jambavan, wise and ancient, whispered, “There is hope. The Sanjeevani herb, found on the mountain of Dronagiri in the far north—it can save them. Hanuman, only you can go.” Hanuman did not wait. He leapt into the sky like a blazing comet.<br />
            <br />The night was cruel. Wind howled. Lightning tore the clouds. Hanuman reached the mountain but could not find the herb among thousands of plants. So with mighty determination, he uprooted the entire mountain and carried it across the sky. The glow of the life-giving herbs lit the darkness beneath him. When he returned, the air filled with the scent of hope. The herbs touched Rama and Lakshmana—and breath returned to their chests. The army roared with joy, their spirits blazing anew.<br />
            <img src={yuddha8} id="img8" className="float-left" alt="" />
            <img src={yuddha9} id="img9" className="float-right" alt="" />
            <br />The war only grew fiercer. Kumbhakarna, Ravana’s giant brother, awakened from his cursed slumber. Towering, monstrous, yet noble-hearted in his own way, he marched to battle. He knew his brother was wrong, yet his loyalty was bound by duty. He fought hard, tearing through Vanara troops. But Rama, with calm dignity, faced him. Their battle shook the heavens, and finally, an arrow from Rama’s bow struck true—Kumbhakarna fell like a mountain collapsing, whispering Rama’s name as the earth embraced him.<br />
            <br />Ravana’s pride cracked. His laughter vanished. His sons were gone, his brothers fallen, yet his arrogance clung to him like chains. He prepared for his final battle. He stood before his mirror, looked at his faces—some furious, some sad, some frightened—and wrapped his armor one last time.<br />
            <br />Rama too stood silent, the morning of destiny upon him. As he stepped into his chariot, the sun broke through the clouds. Vibheeshana stood beside him, whispering strategies. Lakshmana held the reins. The wind grew still.<br />
            <br />When Rama and Ravana faced each other on the battlefield, time itself seemed to stop. Every eye watched. Every heart trembled. Ravana roared, his arrows like flaming serpents. Rama answered, each arrow guided not by anger, but by righteousness.<br />
            <br />The sky darkened with astras. Weapons of fire, wind, water, and darkness collided, shaking the foundations of earth. At last, as the sun hung low, Rama drew the Brahmastra—the divine arrow given by Brahma himself. He closed his eyes and whispered, “For dharma, for Sita, for the world.” The arrow flew like a beam of truth, piercing Ravana’s heart.<br />
            <img src={yuddha10} id="img10" className="float-left" alt="" />
            <br />Ravana staggered. One by one, his ten heads bowed. His arms shook. In his eyes, for a moment, there was not hatred—but relief. As he fell, the air sighed. The war ended.
            <br />Rama stood in silence, his bow lowered. There was no joy in his face, only a deep, indescribable sorrow—like a man who had won the world but lost parts of his soul in the fire.<br />
            <br />Sita was brought to him, her eyes brimming with tears, her hands trembling. Rama looked at her—not as a warrior, but as a husband who had walked through fire and blood to keep a promise. And yet, the story of their hearts was not done—it was about to face the purest, yet cruelest test of all.<br />
            <br />The battlefield had gone strangely quiet. The cries of war, the thunder of arrows, and the clash of iron had faded into an eerie silence, as though the land itself held its breath. A mist of dust and grief hung in the air, lit dimly by the setting sun. Ravana’s body lay still upon the blood-soaked ground—his armor shattered, his ten heads bowed at last to fate. The winds that once carried his proud laughter now blew softly, almost mournfully, across the ruins of Lanka.<br />
            <br />Rama stood still beside his chariot, his bow lowered, his eyes fixed upon the fallen king. There was no triumph in his face, no trace of pride—only a profound quietness, like the stillness of a deep ocean after a raging storm. He whispered a prayer for Ravana’s soul, acknowledging not the demon he became, but the scholar, the devotee of Shiva, the once-noble king lost to arrogance.<br />
            <br />As dusk turned to twilight, Vibheeshana approached silently, his face clouded by pain. He knelt before Rama, tears glistening in his eyes. “My lord, he was my brother… and yet you gave him honor even in death. Allow me to perform his final rites.” Rama placed a hand gently on Vibheeshana’s shoulder and nodded. “He died a warrior. Let his funeral be worthy of the king he once was.” At those words, even the gods watching from above bowed their heads in respect.<br />
            <br />While the pyre of Ravana was prepared in silence, another figure was led gently toward Rama—a woman draped in a simple, torn sari, her face pale but radiant with hope. Sita. Her footsteps faltered as she reached him, her heart a tempest of joy, pain, and longing. For a moment, she stood still, drinking in the sight of him—his golden skin smeared with battle ash, his eyes tired yet filled with an unfathomable depth of love and sorrow.<br />
            <br />“Rama…” Her voice trembled, barely a whisper.
            <br />He looked at her—truly looked at her—as though after many lifetimes of searching, his eyes had found their home. Yet, behind that tenderness lay a shadow. A silence fell heavy between them. The Vanaras who stood nearby felt it too, like a cold wind brushing through their hearts.<br />
            <br />Rama spoke softly, his voice steady but distant, as though each word was weighed against his own soul. “I have done my duty. I fought this war not merely for my grief, nor only for my love, but to uphold dharma. I have defeated Ravana, destroyed his pride, and rescued you. But, Sita…” He hesitated, his chest rising with a silent ache. “You have lived in the house of another man. Though I know your heart is pure, the world… the world may not.”<br />
            <br />Sita froze. The color drained from her face. For a moment, she could not breathe. Around them, the wind fell silent, even the ocean seemed to pause. Lakshmana’s fingers clenched around his bow; Hanuman lowered his head, his heart twisting in agony. None dared speak.<br />
            <br />Sita stepped forward, tears glimmering but not falling. Her voice, though fragile, carried the strength of mountains. “My lord, you doubt me?” Rama closed his eyes, the pain in him deeper than any wound. “Not for myself. Never. But for the eyes of the world. A king must be above question.”<br />
            <img src={yuddha11} id="img11" className="float-left" alt="" />
            <br />The world shattered around her words. Yet instead of breaking, Sita straightened her spine, her sorrow turning into a quiet, holy fire. “Then I shall prove my purity,” she said. “Let the sacred fire judge me.”
            <br />A pyre was built—tall flames dancing like spirits of destiny. The sky darkened, clouds gathering as if heaven itself watched with bated breath. Sita walked toward the flames with hands joined, eyes closed. Each step echoed with grace, dignity, and an unbreakable truth. Hanuman fell to his knees, whispering prayers, his heart cracking with devotion. Lakshmana’s eyes burned with unshed tears.<br />
            <br />As she stood at the edge of the fire, she turned one last time toward Rama. “If I have been faithful in body and soul, may Agni, the god of fire, protect me. If not, let these flames consume me.”<br />
            <br />And she walked into the fire.
            <br />A gasp rippled through the army. Some shut their eyes; others cried out in anguish. The flames rose, golden and fierce, wrapping around her like a blazing veil. But she did not scream. She did not burn. Instead, the fire softened around her as though recognizing something sacred.<br />
            <br />Moments later, the flames parted, and from within emerged Agni himself—the fire god, bathed in radiant light. In his arms stood Sita, untouched, glowing with a purity no shadows could stain. Agni bowed before Rama. “She is pure. Her devotion to you is unsullied. Take her back, O righteous king, for there is no blemish upon her soul.”<br />
            <img src={yuddha12} id="img12" className="float-right" alt="" />
            <br />Rama’s eyes filled with tears—not of doubt now, but of overwhelming relief and remorse. He stepped forward, his voice breaking as he said, “Forgive me, Sita. I did what a king must, but my heart… my heart never doubted you.” Sita bowed her head, tears finally spilling down her cheeks—but they were tears of peace.<br />
            <br />He reached out and took her hand—soft, familiar, trembling. And in that touch, all the storms of separation, all the fires of anguish, melted away.<br />
            <br />The war was over. The darkness was gone.<br />
            <br />But their journey… their destiny… was not yet complete.<br />
            <br /><br />
          </p>
      </div>
    </div>
  );
}

export default YuddhaKanda;